name: Deploy frontend to production
on:
  push:
    branches:
      - main
jobs:
  deployment:
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://www.ausmon.org.au
    steps:
      - run: echo "🚀 Deployment was automatically triggered by a ${{ github.event_name }} event. 🚀"
      - name: checkout repo
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: install
        run: make install
      - name: deploy
        run: make deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "ap-southeast-2"
      - run: echo "Successfully deployed to production 🎉"
