name: Deploy frontend to S3
on:
  push:
    branches:
      - main
jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🚀 Deployment was automatically triggered by a ${{ github.event_name }} event. 🚀"
      - run: make deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'ap-southeast-2'
      - run: echo "Successfully deployed 🎉"
